// Generated by @wagmi/cli@0.1.11 on 3/7/2023 at 5:29:52 PM
import {
  getContract,
  GetContractArgs,
  readContract,
  ReadContractConfig,
  writeContract,
  WriteContractMode,
  WriteContractArgs,
  WriteContractPreparedArgs,
  WriteContractUnpreparedArgs,
  prepareWriteContract,
  PrepareWriteContractConfig,
  watchContractEvent,
  WatchContractEventConfig,
  WatchContractEventCallback,
} from 'wagmi/actions'

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Lock
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

/**
 * [__View Contract on Sepolia Etherscan__](https://sepolia.etherscan.io/address/0x7006DCaEF839059abaD89710030E8742785bf960)
 */
export const lockABI = [
  {
    stateMutability: 'payable',
    type: 'constructor',
    inputs: [{ name: '_unlockTime', internalType: 'uint256', type: 'uint256' }],
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'amount',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
      {
        name: 'when',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'Withdrawal',
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'owner',
    outputs: [{ name: '', internalType: 'address payable', type: 'address' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'unlockTime',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [],
    name: 'withdraw',
    outputs: [],
  },
] as const

/**
 * [__View Contract on Sepolia Etherscan__](https://sepolia.etherscan.io/address/0x7006DCaEF839059abaD89710030E8742785bf960)
 */
export const lockAddress = {
  11155111: '0x7006DCaEF839059abaD89710030E8742785bf960',
} as const

/**
 * [__View Contract on Sepolia Etherscan__](https://sepolia.etherscan.io/address/0x7006DCaEF839059abaD89710030E8742785bf960)
 */
export const lockConfig = { address: lockAddress, abi: lockABI } as const

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Core
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

/**
 * Wraps __{@link getContract}__ with `abi` set to __{@link lockABI}__.
 *
 * [__View Contract on Sepolia Etherscan__](https://sepolia.etherscan.io/address/0x7006DCaEF839059abaD89710030E8742785bf960)
 */
export function getLock(
  config: Omit<GetContractArgs, 'abi' | 'address'> & {
    chainId?: keyof typeof lockAddress
  },
) {
  return getContract({
    abi: lockABI,
    address: lockAddress[11155111],
    ...config,
  })
}

/**
 * Wraps __{@link readContract}__ with `abi` set to __{@link lockABI}__.
 *
 * [__View Contract on Sepolia Etherscan__](https://sepolia.etherscan.io/address/0x7006DCaEF839059abaD89710030E8742785bf960)
 */
export function readLock<
  TAbi extends readonly unknown[] = typeof lockABI,
  TFunctionName extends string = string,
>(
  config: Omit<ReadContractConfig<TAbi, TFunctionName>, 'abi' | 'address'> & {
    chainId?: keyof typeof lockAddress
  },
) {
  return readContract({
    abi: lockABI,
    address: lockAddress[11155111],
    ...config,
  } as unknown as ReadContractConfig<TAbi, TFunctionName>)
}

/**
 * Wraps __{@link writeContract}__ with `abi` set to __{@link lockABI}__.
 *
 * [__View Contract on Sepolia Etherscan__](https://sepolia.etherscan.io/address/0x7006DCaEF839059abaD89710030E8742785bf960)
 */
export function writeLock<
  TFunctionName extends string,
  TMode extends WriteContractMode,
  TChainId extends number = keyof typeof lockAddress,
>(
  config:
    | (Omit<
        WriteContractPreparedArgs<typeof lockABI, TFunctionName>,
        'abi' | 'address'
      > & {
        mode: TMode
        chainId?: TMode extends 'prepared' ? TChainId : keyof typeof lockAddress
      })
    | (Omit<
        WriteContractUnpreparedArgs<typeof lockABI, TFunctionName>,
        'abi' | 'address'
      > & {
        mode: TMode
        chainId?: TMode extends 'prepared' ? TChainId : keyof typeof lockAddress
      }),
) {
  return writeContract({
    abi: lockABI,
    address: lockAddress[11155111],
    ...config,
  } as WriteContractArgs<typeof lockABI, TFunctionName>)
}

/**
 * Wraps __{@link prepareWriteContract}__ with `abi` set to __{@link lockABI}__.
 *
 * [__View Contract on Sepolia Etherscan__](https://sepolia.etherscan.io/address/0x7006DCaEF839059abaD89710030E8742785bf960)
 */
export function prepareWriteLock<
  TAbi extends readonly unknown[] = typeof lockABI,
  TFunctionName extends string = string,
>(
  config: Omit<
    PrepareWriteContractConfig<TAbi, TFunctionName>,
    'abi' | 'address'
  > & { chainId?: keyof typeof lockAddress },
) {
  return prepareWriteContract({
    abi: lockABI,
    address: lockAddress[11155111],
    ...config,
  } as unknown as PrepareWriteContractConfig<TAbi, TFunctionName>)
}

/**
 * Wraps __{@link watchContractEvent}__ with `abi` set to __{@link lockABI}__.
 *
 * [__View Contract on Sepolia Etherscan__](https://sepolia.etherscan.io/address/0x7006DCaEF839059abaD89710030E8742785bf960)
 */
export function watchLockEvent<
  TAbi extends readonly unknown[] = typeof lockABI,
  TEventName extends string = string,
>(
  config: Omit<
    WatchContractEventConfig<TAbi, TEventName>,
    'abi' | 'address'
  > & { chainId?: keyof typeof lockAddress },
  callback: WatchContractEventCallback<TAbi, TEventName>,
) {
  return watchContractEvent(
    {
      abi: lockABI,
      address: lockAddress[11155111],
      ...config,
    } as WatchContractEventConfig<TAbi, TEventName>,
    callback,
  )
}
